### ISSUE TITLE
KeyError: 'charttime' 

### ISSUE THREAD

**Issue by LyapunovStability** [Chenliu-svg/DDL-CXR#1]
Traceback (most recent call last):
  File "..\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "..\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "..\DDL-CXR\mimic4extract\mimic3benchmark\scripts\extract_subjects_iv.py", line 103, in <module>
    read_events_table_and_break_up_by_subject(f'{args.mimic3_path}', table, args.output_path, items_to_keep=items_to_keep,
  File "..\DDL-CXR\mimic4extract\mimic3benchmark\mimic3csv.py", line 224, in read_events_table_and_break_up_by_subject
    'charttime': row['charttime'],
KeyError: 'charttime'

**Comment by Chenliu-svg** [comment]
Hi, @LyapunovStability 
Since I can reproduce the data preprocessing at my end, here are a few things you can do to help fix the bug you have encountered at your end:
1. Please check if the mimic-iv dataset you have downloaded is the 2.0 version. As earlier or later versions might have different table attributes.
2. If the version is right, run `head {path/to/the/mimiciv/2.0/icu/chartevents.csv}` on your Linux terminal, you shall see the following output:
```text
subject_id,hadm_id,stay_id,charttime,storetime,itemid,value,valuenum,valueuom,warning
10000032,29079034,39553978,2180-07-23 12:36:00,2180-07-23 14:45:00,226512,39.4,39.4,kg,0
10000032,29079034,39553978,2180-07-23 12:36:00,2180-07-23 14:45:00,226707,60,60,Inch,0
10000032,29079034,39553978,2180-07-23 12:36:00,2180-07-23 14:45:00,226730,152,152,cm,0
```
Since the line 224 in "..\DDL-CXR\mimic4extract\mimic3benchmark\mimic3csv.py" is to read the `charttime` attribute from the original `chartevents.csv`, so the bug might be associated with the original data. Please feel free to comment if the bug remains.

Thanks.

**Comment by LyapunovStability** [comment]
@Chenliu-svg 
Thank you for your prompt response. I appreciate your fascinating and impressive work, and I'm eager to explore more about this research. 

I have another question regarding the code in the `Class EHR_pickler` of `dynamic_data.py`:

```python
if cha >= 12:
    ts_interval = ts_df[(ts_df.Hours >= (48 - cha)) & (ts_df.Hours <= 48)].reset_index(drop=True).fillna("").values
else:
    ts_interval = ts_df[(ts_df.Hours >= 36) & (ts_df.Hours <= 48)].reset_index(drop=True).fillna("").values
```

I believe this code is preparing the corresponding EHR for the most recent CXR (e.g., x_1) to generate an up-to-date Z. However, It seems that 'cha' only represents the time difference between image pairs (x_0, x_1), why not use the absolute time (e.g., [t_x1, 48]) to filter the EHR?

**Comment by Chenliu-svg** [comment]
Hi, @LyapunovStability 

Thank you for your interest in our work and your questions. Please kindly check the updated `Class EHR_pickler` in the `dynamic_data.py` file, and find my reply to your confusion below. In the `Class EHR_pickler`, three functions are defined to process three kinds of EHR data:
- The function `_ehr_pickle_dm` is used to create EHR data for the ldm stage. The EHR data is extracted between CXR image pairs using the fields `left_time` and `right_time` (i.e., [t_x0, t_x1]).
- The function `_ehr_pickle_gen` is designed to prepare EHR data used to generate the updated Z for the prediction. The EHR data is extracted from the last available CXR taken time to the prediction time (48h), and the `cha` field in the `{train\validate\test}_pred.csv` files records this. Please refer to the `pre_processing.py` file for more details.
- The function `_ehr_pickle_pred` is to prepare EHR data for prediction, where a full 48 hours of EHR data are used.

I hope this clarifies your confusion.

Thanks.
